### ISSUE TITLE
Align workflow triggers

### ISSUE THREAD

**Issue by haani-niyaz** [rog-golang-buddies/golang-template-repository#43]
All workflows do not have a consistent trigger mechanism. The following workflows should have a consistent trigger and if not, should be documented via a comment on why it is different. Alignment on this would also set the defaults for future workflows we setup.

```
name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]
...
```  

```
name: Gitleaks
on: [pull_request, push, workflow_dispatch]
...
```

```
name: Go-Test
on:
  [pull_request, push, workflow_dispatch]
...
```  

```
name: golangci-lint
on:
  push:
  pull_request: 
...
```   

_The following seems obvious but added here for completeness._

```
name: gen-docs
on:
  push:
    branches:
      - main
...
```      

```
name: release
on:
  push:
    branches:
      - main
 ...
```
